Summary:     Provides diff file statistics
Summary(de): Liefert diff-Datei-Statistiken
Summary(fr): Fournit des statistiques sur les différences de fichiers.
Summary(pl): Umo¿liwia robienie statystyk plików diff
Summary(tr): diff dosyasý istatistik bilgileri çýkarýr
Name:        diffstat
Version:     1.25
Release:     7
Copyright:   distributable
Group:       Utilities/Text
Group(pl):   Narzêdzia/Tekst
Source:      ftp.clark.net:/pub/dickey/diffstat/%{name}-%{version}.tgz
Buildroot:   /tmp/%{name}-%{version}-root

%description
'diffstat' provides a number of statistics on a patch generated by diff,
including number of additions, number of removals, and total number of
changes. It can be useful, for example, to find out what changes have been
made to a program, just by feeding the update patch to diffstat.

%description -l de
'diffstat' stellt eine Reihe von statistischen Informationen für mit 
Patch erzeugte Diffs bereit, u.a. die Zahl der Einfügungen, der Streichungen
sowie die Gesamtzahl der Änderungen. So ist es möglich, die Änderungen an 
einem Programm zu ermitteln, indem man das Update-Patch durch diffstat
durchlaufen läßt. 

%description -l fr
« diffstat » offre de nombreuses statistiques sur un patch généré par diff,
cela comprend le nombre d'ajouts, de suppressions et le nombre total de
modifications. Il peut être utile, par exemple, de retrouver les modifications
faites à un programme en fournissant uniquement le patch de mise à jour à
diffstat.

%description -l pl
Diffstat umo¿liwia prowadzenie statystyk pliku (³atki) generowanego 
przez diff. Pakiet ten mo¿e byæ u¿yteczny, na przyk³ad w poszukiwaniu 
zmian, które zosta³y dokonane w jakim¶ programie. 

%description -l tr
diffstat programý, diff tarafýndan üretilen bir yama üzerinden toplama
sayýsý, çýkarma sayýsý, toplam deðiþiklik sayýsý gibi bazý istatistiksel
bilgiler çýkartýr.

%prep
%setup -q

%build
./configure %{_target} --prefix=/usr
make CPPFLAGS="$RPM_OPT_FLAGS" LDFLAGS="-s"

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT/usr/{bin,man/man1}

install diffstat $RPM_BUILD_ROOT/usr/bin
install diffstat.1 $RPM_BUILD_ROOT%{_mandir}/man1

gzip -9nf $RPM_BUILD_ROOT%{_mandir}/man1/*
gzip -9nf README CHANGES

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644, root, root, 755)
%doc README.gz CHANGES.gz
%attr(755, root, root) /usr/bin/*
%attr(644, root,  man) %{_mandir}/man1/*

%changelog
* Wed Feb 17 1999 Micha³ Kuratczyk <kura@wroclaw.art.pl>
  [1.25-7]
- added gzipping man page and documentation
- added Group(pl)

* Thu Jul 23 1998 Wojtek ¦lusarczyk <wojtek@shadow.eu.org>
  [1.25-6]
- added pl translation,
- added buildroot support,
- build from non root's account,
- minor changes.

* Mon Apr 27 1998 Prospector System <bugs@redhat.com>
- translations modified for de, fr, tr

* Thu Jul 10 1997 Erik Troan <ewt@redhat.com>
- built against glibc
